DROP DATABASE IF EXISTS T9_DDBBPinturilloSO;
CREATE DATABASE T9_DDBBPinturilloSO;
USE T9_DDBBPinturilloSO;

CREATE TABLE Jugadores (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Usuario VARCHAR(80) NOT NULL,
    Correo VARCHAR(80) NOT NULL,
    Contrasena VARCHAR(80) NOT NULL,
    FotoPerfil INTEGER NOT NULL,
    Puntos INTEGER DEFAULT 0,
    FraseFavorita VARCHAR(100)
);

CREATE TABLE Partidas (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    Codigo VARCHAR(5) NOT NULL,
    MaximoJugadores INTEGER NOT NULL,
    Categoria VARCHAR(80) NOT NULL,
    Dificultad VARCHAR(80) NOT NULL,
    Rondas INTEGER NOT NULL,
    Privacidad VARCHAR(80) NOT NULL,   
    Fecha DATE NOT NULL
);

CREATE TABLE Dibujos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Dibujo VARCHAR(80) NOT NULL,
    Dificultad INTEGER NOT NULL,
    Categoria VARCHAR(80) NOT NULL
);

CREATE TABLE PartidasJugadas (
    PartidaID INTEGER NOT NULL,
    PrimeroID INTEGER NULL,
    SegundoID INTEGER NULL,
    TerceroID INTEGER NULL,
    CuartoID INTEGER NULL,
    GanadorID INTEGER NULL,
    FOREIGN KEY (PartidaID) REFERENCES Partidas(ID),
    FOREIGN KEY (PrimeroID) REFERENCES Jugadores(ID) ON DELETE SET NULL,
    FOREIGN KEY (SegundoID) REFERENCES Jugadores(ID) ON DELETE SET NULL,
    FOREIGN KEY (TerceroID) REFERENCES Jugadores(ID) ON DELETE SET NULL,
    FOREIGN KEY (CuartoID) REFERENCES Jugadores(ID) ON DELETE SET NULL,
    FOREIGN KEY (GanadorID) REFERENCES Jugadores(ID) ON DELETE SET NULL
);

CREATE TABLE Amigos (
    JugadorID INTEGER NOT NULL,
    AmigoID INTEGER NOT NULL,
    FOREIGN KEY (JugadorID) REFERENCES Jugadores(ID) ON DELETE CASCADE,
    FOREIGN KEY (AmigoID) REFERENCES Jugadores(ID) ON DELETE CASCADE,
    CHECK (JugadorID <> AmigoID)
);
